index.js, package.json
This PR adds a progress bar as it downloads the files.
=> feat: Download Progress Bar

index.js
This modification had mysteriously disappeared somehow... Sus Amogus? 😏 
So, here's another PR that does the same thing as #48
=> [reapply] fix(temp): dirty workaround to a bug introduced by the CLI

Dockerfile, README.md
- add Dockerfile
- change README / add docker instructions
=> feat: Add Dockerfile for building revanced using docker

.github/workflows/build.yml
The title is self explanatory.
=> Change the workflow for the new update

src/ui/patchesScreen.js
* Added ADB debugging steps to "Couldn't find device" error popup
* Made help link follow the standard for links
* Add ADB 15 second installer link
=> Add ADB debugging steps

index.js
=> fix: always use ReVanced's aapt2 on android

public/index.js, wsEvents/GetAppVersion.js
let's just say i didn't mess with `isDownloading`
i have no idea how to do it your way 
if you don't wanna merge this and fix it that way, sure
but this works and its all that matters
=> fix: "You didn't select an app version!" when downloading yt app for root

public/index.html, utils/downloadApp.js, wsEvents/GetAppVersion.js
I still don't get why WarnWetter, out of all things, is one of the *officially* supported apps to be patched, but anyways...
=> feat: support for WarnWetter

wsEvents/GetPatches.js
name and description are now combined correctly and the code/regex was simplified a bit
`patchList` before vs after:
=> fix: patch list extraction

.gitignore, Dockerfile, index.js, package-lock.json, public/index.js
Closes  #160
I changed a few things:
1. Make WebSocket URI dynamic based on the current URL
2. Some improvements on the Dockerfile*
3. Add a button to download the compiled file after the build
Example using a remote server:
https://user-images.githubusercontent.com/5548950/183228316-a088176c-3fb2-42e1-83d2-8cf0fb276cde.mov
\*I don't know if you had `npm install` as part of the `CMD` for a reason I currently don't understand. I moved it to the build part
=> Adapt to work remotely

index.js, package-lock.json, package.json, public/index.js, public/styles/dependencies.css, utils/FileDownlader.js, utils/PatchListRememberer.js, wsEvents/GetAppVersion.js, wsEvents/PatchApp.js, wsEvents/UpdateFiles.js
<sup> I definitely have tested my code this time 😹 </sup>
=> feat: attempt opening the app directly in the default browser

public/index.html, public/index.js, public/patches/index.html, wsEvents/GetPatches.js
another minor update: we can press enter on website to continue
=> feat: Show maximum supported version for patch while selecting patches

wsEvents/SelectAppVersion.js
=> fix: apkInfo is NOT defined before! (I'm dumb)

wsEvents/PatchApp.js
=> fix: input=jarNames.selectedApp, output=revanced.apk

public/index.js, public/styles/core.css, wsEvents/GetAppVersion.js, wsEvents/PatchApp.js, wsEvents/SelectAppVersion.js
=> feat: auto-scroll patch logs 

wsEvents/GetAppVersion.js
since some ppl wanted to use v17.29.34, lists up to 30 versions now:
=> feat: scrape more apkmirror versions

android-interface.sh
Updating the wiki's up to you, Reis.
=> feat: add a "cli" for android

android-interface.sh
It was creating structures like revanced-builder/revanced-builder/...
This should _probably_ fix it.
=> fix: the update command

public/styles/core.css
=> Accessibility: Buttons should have a hand cursor so it looks clickable.

public/styles/apps.css
Before and After:
https://user-images.githubusercontent.com/102938585/186217181-18a3dfce-90c3-4cd2-9260-78f144da6cf1.mp4
=> Cosmetic change: make lists more beautiful.

public/styles/core.css
1. Added pointer cursor and hover box-shadow to these icons:
2. Customized buttons to follow overall ui design:
=> Cosmetic change v3: added box-shadow to footer buttons

public/about/index.html, public/dependencies/index.html, public/failure/index.html, public/index.html, public/index.js, public/patch/index.html, public/patches/index.html, public/styles/core.css, public/styles/fontawesome.css, public/versions/index.html
=> Added accent color picker 😎

wsEvents/GetPatches.js
fixes #326 with general solution for all possible duplicate patches
=> distinct array from set

index.js
This adds a way to disable the automatic browser opening when the program is starting.
=> feat: add `--no-open`

public/exitted/index.html, public/index.js, wsEvents/GetAppVersion.js
- feat[enhancement]: add exit page on clicking Quit button
- fmt: npm run fmt
=> exitApp imprvovements

utils/downloadApp.js, wsEvents/getAppVersion.js, wsEvents/selectAppVersion.js
=> Fix not downloading

public/patches/index.html, public/styles/patches.css
=> cosmetic change: style search box

public/index.html
No need to load whole index.js it affects page load time.
=> Fix: broken about and github buttons on homepage

public/apps/index.html, public/index.html, public/index.js, public/styles/core.css, public/styles/home.css, wsEvents/checkForUpdates.js
old updater used to annoy user and disturb them by showing a popup, the current one doesn't shows any popup only static elements on homepage and it also shows current version of builder.
=> added new and better updater!

docker-compose.yml
Must use:  
docker-compose build --no-cache
docker-compose up -d
=> Created docker-compose.yml

public/index.js
* Made the search function use `ES6` array functions
* Search now uses `include` instead of `startsWith`
=> Fix Patch Search Function

public/about/index.html, public/apps/index.html, public/colors.js, public/dependencies/index.html, public/devices/index.html, public/failure/index.html, public/index.html, public/index.js, public/installer/index.html, public/patch/index.html, public/patches/index.html, public/settings.js, public/settings/index.html, public/styles/core.css, public/styles/fontawesome.css, public/styles/settings.css, public/versions/index.html
please ignore typo on commit message :sweat_smile: 
btw here we go for screenshot:
=> Introducing Automatically proceed to next page and a Settings page!

README.md, docker-compose.yml, public/about/index.html, public/apps/index.html, public/dependencies/index.html, public/devices/index.html, public/failure/index.html, public/index.html, public/index.js, public/installer/index.html, public/patch/index.html, public/patches/index.html, public/settings.js, public/settings/index.html, public/styles/about.css, public/styles/core.css, public/styles/home.css, public/styles/patches.css, public/styles/settings.css, utils/PatchListRememberer.js, wsEvents/getAppVersion.js
- Introducing Pure Black theme
- Changed footer icons onclick event to link
- Footer can become scrollable on small devices now
- New About Page
- Some other accessibility changes and bug fixes
=> feat(frontend): pure black theme

public/index.js, public/versions/index.html
I forgot to push these changes with the last pr, sorry :sweat_smile:
=> quick fixes

public/styles/home.css
=> Make homepage properly scrollable

public/index.html, public/styles/home.css, public/styles/patches.css
=> final homepage fix

.github/workflows/build.yml
Changelog: https://github.com/ProcursusTeam/ldid/releases/
=> Update `ProcursusTeam/ldid` to `v2.1.5-procursus7`

android-interface.sh
** Avoid using if-then-else when not really necessary
** Improve help dialogs a bit
=> android-interface: Optimize code structure and improve strings

android-interface.sh
** Don't know how i didn't notice this :/
=> android-interface: Fixup
