reisxd/revanced-builder

.github/workflows/build.yml
This PR adds a GitHub Actions Workflow to build binaries for Windows, MacOS and Linux whenever a tag in the form of `v*.*.*`, where * is some integer, is pushed. Other commits would not trigger the workflow.
E.g.:
1. This triggers the workflow
```bash
$ git tag v1.2.0
$ git push origin main --tags
```
2. This won't
```bash
$ git tag abcdefgh # won't work
```
3. This won't, too
```bash
$ git tag v1.2.0
$ git push origin main # --tags should be there to push the tags to upstream
```
=> ci: add workflow to build binaries and release

flake.lock, flake.nix
This PR adds support for installing the deps with the NIx package manager. If you have NIx installed, all you have to do to use this tool is the following:
```bash
nix develop # This opens a new shell environment with the deps, without having to install them. This also automatically runs npm install.
node . --patch # Or whatever your patch command is
```
=> Added support for Nix

index.js
The `revanced-cli` apparently uses the line endings depending upon the platform:
- Windows: `\r\n`
- *Nix (Unix, Linux, MacOS, Android...): `\n`
This PR fixes the regex to rip the patch descriptions so that the EOL set by the platform is used, instead of hardcoding `\r\n`
fix #38 
Edit: Seems like Prettier did a LOT of changes, ignore them. The actual thing is from line 482~484
=> fix: use `os.EOL` for patchDescsArray

README.md, index.js
Made it possible to include patches and fixed a small bug.
**Bug Fix**
When only excluding one patch, it would exclude the patch twice.
Example:
Input:
```bash
node . --patch --exclude disable-shorts-button
```
Produced ReVanced CLI command:
```bash
java -jar ${jarNames.cli} -b ${jarNames.patchesJar} --experimental -a ./revanced/youtube.apk ${jarNames.deviceId} -o ./revanced/revanced.apk -m ${jarNames.integrations} -e disable-shorts-button -e disable-shorts-button
```
How it should be:
```bash
java -jar ${jarNames.cli} -b ${jarNames.patchesJar} --experimental -a ./revanced/youtube.apk ${jarNames.deviceId} -o ./revanced/revanced.apk -m ${jarNames.integrations} -e disable-shorts-button
```
The double exclude doesn't really hurt but I fixed it anyway.
=> Explicitly include patches

index.js
We're "tricking" the CLI to think we're giving it the
YouTube APK via `-a`, when all we are doing is simply passing it its own
integrations APK. This will be definitely reverted as soon as the CLI
fixes the weird issue.
Close #47
=> fix(temp): dirty workaround to a bug introduced by the CLI

public/index.js, public/styles/dependencies.css
Styles for span.log didn't apply when logs from stderr were wrapped inside a `<div style="color: red;">`. This made the log distorted.
This change would make it so that *every* log line would be wrapped with `span.log-line`, and the base styles are applied for this. If the logs are from stderr, an extra class `.stderr` would be added.
=> fix: stderr log lines getting squished together

index.js, utils/downloadApp.js, utils/mountReVanced.js, wsEvents/PatchApp.js, wsEvents/SelectAppVersion.js
=> feat: rename output APK with info about the build

wsEvents/PatchApp.js
We don't need just a `v` in the name
=> fix: make part3 empty if version is nullish

index.js, package-lock.json, package.json
This will fix an issue where the app fails to run when 8080 is already in use.
resolves #217
=> feat: listen at a dynamically generated port

utils/mountReVanced.js
Refer to
https://github.com/TeamVanced/VancedManager/blob/compose/app/src/main/java/com/vanced/manager/installer/util/Patcher.kt#L88
About "-mm" option for su 
https://github.com/topjohnwu/Magisk/blob/master/docs/tools.md#su
```
-mm, -M,
--mount-master                force run in the global mount namespace
```
=> fix mount command so it doesn't require restart

package-lock.json, package.json, public/index.js, utils/FileDownloader.js, utils/mountReVanced.js, wsEvents/GetAppVersion.js, wsEvents/GetPatches.js, wsEvents/PatchApp.js
Showing beta versions will not be a problem, right?
_Right?_
(also i have no idea why my prettier dislikes spaces before function arguments)
=> Show beta versions, recommended versions and sort by version number instead of upload date

wsEvents/GetAppVersion.js
=> fix: broken version check

public/index.js
=> fix: styles on the version select page

android-interface.sh
=> fix: use extglob to exclude . and .. in `mv`

wsEvents/GetPatches.js
now the array used is truly distinct based on the regex group "name", previous solution didn't work because matchAll does return a complex array which is not easily distinctable with Set()
_really_ fixes #326 with general solution for all possible duplicate patches
i tested this multiple times (which i did not before, sry)
=> truly distinct array

wsEvents/PatchApp.js
Signed-off-by: shrihanDev <shrihankp198725@gmail.com>
=> fix: `-all` is removed in CLI file names

README.md
As of commit 04a0f9c3e0b1ae868782afa752ea7c6fac88359c, the anchor link for the list of patches has changed. This commit ensures users are sent to the correct spot on the page automatically.
=> fix: Update patches anchor link

android-interface.sh
now the whitenames (greennames?) have no excuse to not see the error
=> feat: color the play store termux error in red

public/index.js
The old code was actually better, because the new one doesn't take in consideration when the currentFile is equal to message.name from the start - that's why the "Downloading youtube.apk..." was not shown.
Reverting this fixes the issue.
You are smart, just trust yourself more 🙃😂
EDIT: AWW SH*T THE DOUBLE LOG 😩
=> Revert "downloadingFile" logging part

android-interface.sh
Now when "./revanced-builder.sh update" is triggered, the script itself is also automatically updated in the home folder.
=> Added cli self-update

android-interface.sh
Now you can run the builder cleaning the cache, but preserving the keystore.
=> feat: added "run --delete-cache-no-keystore"

public/styles/failure.css
Making error logs selectable will make it easier to copy logs or links.
=> Make error logs user selectable

public/styles/patches.css
Chrome allows it by default for input box but idk why firefox doesn't so this fix only targets firefox users.
Firefox applies [this](https://github.com/reisxd/revanced-builder/blob/209a96178a68facbb721d8cc8b0ea54a7a1e4273/public/styles/core.css#L33) to input box too LOL
=> allow text selection in search bar

wsEvents/installReVanced.js
When trying to install the APKs with a space in their folder paths, the command fails as the space separates the folder paths.
Quotes tells the command that the space is part of the folder path (Everything in the quotes is a single path!)
```
Error: Command failed: adb -s (DEVICEIDforPrivacy) install C:\Users\Windows Games\Downloads\revanced\ReVanced-YouTube-v17.36.37-cli_v2.13.0-patches_v2.77.1.apk
adb: failed to stat Games\Downloads\revanced\ReVanced-YouTube-v17.36.37-cli_v2.13.0-patches_v2.77.1.apk: No such file or directory
```
=> Added quotes for paths with spaces

public/apps/index.html, utils/PatchListRememberer.js, utils/downloadApp.js, wsEvents/getAppVersion.js, wsEvents/patchApp.js
=> Added support for Twitch

public/styles/patches.css
While shifting css styles from patches.css to core.css you mistakenly introduced this bug: https://github.com/reisxd/revanced-builder/commit/a7c0524d53092f258e0aebb6ea6c0b6593e1f980
=> Fixed a black theme bug

android-interface.sh
I did this because this would be the way I would run the builder every time to save storage space.
=> New attributes to delete cache after running the builder

README.md
Always attempt to pull a newer version of the image
=> Use `--pull` in docker commands

public/index.js, wsEvents/getAppVersion.js
* Add page switcher for version selection (specifically YouTube) because the recommended version would not appear on the first page of results
Addresses issues #666, #667, #674, #676, #680, #681, and probably more that I'm too lazy to find
Download binaries: https://github.com/imaperson1060/revanced-builder/releases/tag/v3.9.0-pages
Detailed explanation:
* Currently, the version list is pulled from the first page of recent releases for the YouTube app on ApkMirror.
* Since the patches haven't been updated for a while, the recommended version is no longer on the first page of results.
* This PR adds "Next" and "Previous" buttons for page navigation, which allows the recommended version to be selected within Revanced Builder
=> Add page selection for app version

wsEvents/getAppVersion.js
Enables sanitizing multi-digit numbers with a leading zero.
Fixes #648
=> Update regex inside sanitizeVersion
